#desgin file
<Main>:
    BoxLayout:
        orientation:"vertical"

        BoxLayout:
            orientation: 'horizontal'

            Button:
                text: "file"
        
            Button:
                text:"edit"

            Button:
                text:"setting"

            Button:
                text:"help"
        

        TextInput:
            hint_text:"hola"
            color:rgba("#b3ff00") 
